set_property SRC_FILE_INFO {cfile:{/home/frederik/Documents/Rob Electronics/Assignment 1/assignment_1.srcs/constrs_1/new/user_constraint.xdc} rfile:../../../assignment_1.srcs/constrs_1/new/user_constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports A]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports B]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports Y]
