set_property IOSTANDARD LVCMOS33 [get_ports Y]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property PACKAGE_PIN L15 [get_ports A]
set_property PACKAGE_PIN J15 [get_ports B]
set_property PACKAGE_PIN P15 [get_ports Y]