# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/user_constraint.xdc

# Block Designs: bd/xor_gate/xor_gate.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xor_gate || ORIG_REF_NAME==xor_gate}]

# IP: bd/xor_gate/ip/xor_gate_processing_system7_0_0/xor_gate_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xor_gate_processing_system7_0_0 || ORIG_REF_NAME==xor_gate_processing_system7_0_0}]

# IP: bd/xor_gate/ip/xor_gate_xor_component_0_0/xor_gate_xor_component_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xor_gate_xor_component_0_0 || ORIG_REF_NAME==xor_gate_xor_component_0_0}]

# XDC: bd/xor_gate/xor_gate_ooc.xdc
