# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/user_constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_duty_module_0_0/design_1_duty_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_duty_module_0_0 || ORIG_REF_NAME==design_1_duty_module_0_0}]

# IP: bd/design_1/ip/design_1_bldc_decoder_0_0/design_1_bldc_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bldc_decoder_0_0 || ORIG_REF_NAME==design_1_bldc_decoder_0_0}]

# IP: bd/design_1/ip/design_1_pwm_8bit_0_0/design_1_pwm_8bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pwm_8bit_0_0 || ORIG_REF_NAME==design_1_pwm_8bit_0_0}]

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: bd/design_1/ip/design_1_blcd_driver_0_0/design_1_blcd_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blcd_driver_0_0 || ORIG_REF_NAME==design_1_blcd_driver_0_0}]

# IP: bd/design_1/ip/design_1_spi_master_0_0/design_1_spi_master_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_spi_master_0_0 || ORIG_REF_NAME==design_1_spi_master_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# XDC: bd/design_1/design_1_ooc.xdc
