# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constaints.xdc

# Block Designs: bd/Main/Main.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main || ORIG_REF_NAME==Main}]

# IP: bd/Main/ip/Main_xlconstant_0_0/Main_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_xlconstant_0_0 || ORIG_REF_NAME==Main_xlconstant_0_0}]

# IP: bd/Main/ip/Main_processing_system7_0_0/Main_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_processing_system7_0_0 || ORIG_REF_NAME==Main_processing_system7_0_0}]

# IP: bd/Main/ip/Main_HallSensorEmulation_0_0/Main_HallSensorEmulation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_HallSensorEmulation_0_0 || ORIG_REF_NAME==Main_HallSensorEmulation_0_0}]

# IP: bd/Main/ip/Main_blcd_driver_0_0/Main_blcd_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_blcd_driver_0_0 || ORIG_REF_NAME==Main_blcd_driver_0_0}]

# IP: bd/Main/ip/Main_unity_ctrl_0_0/Main_unity_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_unity_ctrl_0_0 || ORIG_REF_NAME==Main_unity_ctrl_0_0}]

# IP: bd/Main/ip/Main_pwm_0_0/Main_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_pwm_0_0 || ORIG_REF_NAME==Main_pwm_0_0}]

# IP: bd/Main/ip/Main_bldc_starter_0_0/Main_bldc_starter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_bldc_starter_0_0 || ORIG_REF_NAME==Main_bldc_starter_0_0}]

# IP: bd/Main/ip/Main_debounce_0_0/Main_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_debounce_0_0 || ORIG_REF_NAME==Main_debounce_0_0}]

# IP: bd/Main/ip/Main_xlconstant_1_0/Main_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_xlconstant_1_0 || ORIG_REF_NAME==Main_xlconstant_1_0}]

# IP: bd/Main/ip/Main_xlconstant_2_0/Main_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_xlconstant_2_0 || ORIG_REF_NAME==Main_xlconstant_2_0}]

# XDC: bd/Main/Main_ooc.xdc
