# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.cache/wt [current_project]
set_property parent.project_path /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part trenz.biz:te0726_m:part0:3.1 [current_project]
set_property ip_output_repo /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.srcs/sources_1/bd/Main/hdl/Main_wrapper.vhd
add_files /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.srcs/sources_1/bd/Main/Main.bd
set_property used_in_implementation false [get_files -all /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.srcs/sources_1/bd/Main/ip/Main_processing_system7_0_0/Main_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.srcs/sources_1/bd/Main/Main_ooc.xdc]
set_property is_locked true [get_files /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.srcs/sources_1/bd/Main/Main.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.srcs/constrs_1/new/constaints.xdc
set_property used_in_implementation false [get_files /home/frederik/Documents/Rob_Electronics/FinalProject/FinalProject.srcs/constrs_1/new/constaints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Main_wrapper -part xc7z010clg225-1


write_checkpoint -force -noxdef Main_wrapper.dcp

catch { report_utilization -file Main_wrapper_utilization_synth.rpt -pb Main_wrapper_utilization_synth.pb }
