set_property IOSTANDARD LVCMOS33 [get_ports {comparator[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {comparator[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {comparator[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports A_in]
set_property IOSTANDARD LVCMOS33 [get_ports A_inh]
set_property IOSTANDARD LVCMOS33 [get_ports B_in]
set_property IOSTANDARD LVCMOS33 [get_ports B_inh]
set_property IOSTANDARD LVCMOS33 [get_ports C_in]
set_property IOSTANDARD LVCMOS33 [get_ports C_inh]
set_property PACKAGE_PIN K13 [get_ports A_in]
set_property PACKAGE_PIN J13 [get_ports A_inh]
set_property PACKAGE_PIN K11 [get_ports B_in]
set_property PACKAGE_PIN H14 [get_ports B_inh]
set_property PACKAGE_PIN H11 [get_ports C_in]
set_property PACKAGE_PIN H13 [get_ports C_inh]
set_property PACKAGE_PIN K15 [get_ports {comparator[0]}]
set_property PACKAGE_PIN J14 [get_ports {comparator[1]}]
set_property PACKAGE_PIN H12 [get_ports {comparator[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports rx_i]
set_property IOSTANDARD LVCMOS33 [get_ports tx_o]
set_property PACKAGE_PIN M12 [get_ports rx_i]
set_property PACKAGE_PIN N13 [get_ports tx_o]

set_property IOSTANDARD LVCMOS33 [get_ports {led_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports A_in_1]
set_property IOSTANDARD LVCMOS33 [get_ports A_inh_1]
set_property IOSTANDARD LVCMOS33 [get_ports B_in_1]
set_property IOSTANDARD LVCMOS33 [get_ports B_inh_1]
set_property IOSTANDARD LVCMOS33 [get_ports C_in_1]
set_property IOSTANDARD LVCMOS33 [get_ports C_inh_1]

set_property IOSTANDARD LVCMOS33 [get_ports raw_signal_in]
set_property PACKAGE_PIN L15 [get_ports raw_signal_in]
